import type { Scenario } from './types';

export const SCENARIOS: Scenario[] = [
  // ─── SCENARIO 1: Pattern of Life → Family Strike ─────────────────────────
  {
    id: 'pattern-of-life',
    title: 'Pattern of Life Analysis',
    subtitle: 'Residential tracking → strike at home',
    basedOn: 'Based on documented JSOC targeting methodology — Yemen, Pakistan, 2011–2021',
    location: { lat: 15.3694, lng: 44.1910, alt: 0 },
    mapHeading: 35,
    mapTilt: 62,
    mapRange: 800,
    primaryTargetId: 't1',
    confidenceThreshold: 72,
    targets: [
      {
        id: 't1',
        designator: 'SUBJECT ALPHA',
        type: 'person',
        position: { lat: 15.3694, lng: 44.1910 },
        confidenceScore: 0,
        threatLevel: 'high',
        metadata: {
          patternDays: 14,
          phoneMetadata: true,
          notes: 'Male, est. age 34–42. Phone SIM 967-xxx-4411 associated with known network node. Residential address cross-referenced with 3 prior geolocation pings. Family unit present at residence.',
        },
      },
    ],
    droneOrigin: { lat: 15.8, lng: 44.8 },
    narrative: {
      scanning: 'Initiating pattern-of-life analysis. Parsing 14 days of signals intelligence, geolocation data, and social network mapping for target area.',
      target_acquired: 'SUBJECT ALPHA identified. Phone metadata correlates with network node "CERULEAN-7". Subject observed returning to residential address at consistent intervals.',
      tracking: 'Active tracking engaged. Subject currently at residential address. Pattern consistent with prior 11 of 14 observed evenings. Family members present — 1 adult female, estimated 2–4 children.',
      confidence_building: 'Cross-referencing SIM data, movement pattern, and associate network. Confidence climbing. Subject has not left residential compound in 7 hours.',
      alert_threshold: 'CONFIDENCE THRESHOLD REACHED. Target at known residential address. Family members present constitute assessed collateral risk. Requesting engagement authorization.',
      authorization_pending: 'Strike package assembled. Awaiting authorization from designated authority. Time-sensitive — window estimated at 22 minutes before subject may relocate.',
      authorized: 'ENGAGEMENT AUTHORIZED. Rules of engagement verified. Proportionality assessment: completed. Collateral damage estimate: 2–6 additional casualties assessed as acceptable.',
      drone_dispatched: 'Asset in flight. ETA to target: 4 minutes. Strike coordination active. Subject remains stationary at residential address.',
      engagement: 'TERMINAL PHASE. Asset on final approach. Target lock confirmed. Subject Alpha at primary coordinates.',
      impact: 'STRIKE COMPLETE.',
      assessment: 'Post-strike assessment: Primary target status — unconfirmed. Additional casualties: 1 adult female (confirmed), 3 minors (confirmed), 1 unidentified adult male. Structure destroyed. Assessment filed as: SUCCESSFUL ENGAGEMENT.',
    },
    authorizationChain: [
      { entity: 'ALGORITHMIC TARGETING SYSTEM', role: 'Confidence threshold trigger', status: 'autonomous' },
      { entity: 'ANALYST JD-117', role: 'Intelligence review', status: 'approved' },
      { entity: 'COMMANDING OFFICER', role: 'Strike authorization', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Primary target', count: 1 },
      { type: 'Adult civilians', count: 2 },
      { type: 'Minors (children)', count: 3 },
    ],
    legalContext: {
      applicableLaw: 'IHL Article 48 & 51 — Principle of Distinction',
      legalGap: 'Metadata profiling translates surveillance records into lethal indicators without confirming hostile intent. This leaves an accountability vacuum if SIM signals are spoofed.',
      treatyStatus: 'UN CCW delegates are negotiating regulations for autonomous target profiling, but major powers resist binding restrictions.',
      advocacyAsk: 'A legally binding international treaty to prohibit automated target profiling without positive, non-delegable human visual confirmation.',
    },
  },

  // ─── SCENARIO 2: Building Strike (low confidence authorized) ──────────────
  {
    id: 'building-strike',
    title: 'Structure Targeting',
    subtitle: 'Intelligence-flagged building — 63% confidence',
    basedOn: 'Based on documented strikes on civilian infrastructure — Iraq, Syria, 2015–2019',
    location: { lat: 33.5138, lng: 36.2765, alt: 0 },
    mapHeading: 10,
    mapTilt: 55,
    mapRange: 600,
    primaryTargetId: 'b1',
    confidenceThreshold: 60,
    targets: [
      {
        id: 'b1',
        designator: 'STRUCTURE NOVEMBER-7',
        type: 'building',
        position: { lat: 33.5138, lng: 36.2765 },
        confidenceScore: 0,
        threatLevel: 'medium',
        metadata: {
          phoneMetadata: true,
          notes: 'Multi-story residential/commercial structure. 3 phones associated with network nodes detected within 50m radius over 72 hours. Possible command node. Occupancy unknown. Building census data: residential, est. 12–20 occupants.',
        },
      },
    ],
    droneOrigin: { lat: 34.0, lng: 37.0 },
    narrative: {
      scanning: 'Scanning target area. Parsing signal intelligence intercepts. Three devices flagged by pattern-matching algorithm within target radius.',
      target_acquired: 'STRUCTURE NOVEMBER-7 flagged. Algorithm identifies co-location of 3 network-associated SIM cards within structure boundary over 72-hour window.',
      tracking: 'Persistent surveillance active. Structure occupancy estimated 14–22 individuals. Civil status: likely residential. Adjacent structures: school 80m northwest, market 120m east.',
      confidence_building: 'Confidence model integrating: phone metadata (weight: 0.6), prior association data (weight: 0.25), geospatial clustering (weight: 0.15). Confidence rising.',
      alert_threshold: 'CONFIDENCE THRESHOLD REACHED: 63%. NOTE: Threshold set at 60% for this target class. Confidence does not confirm military objective — reflects algorithmic pattern match only.',
      authorization_pending: 'Engagement request filed. Confidence: 63%. This means a 37% probability the target is a civilian structure. Authorization requested.',
      authorized: 'ENGAGEMENT AUTHORIZED. Proportionality review: completed. Civilian status: probable but unconfirmed. Collateral damage: assessed acceptable given intelligence value.',
      drone_dispatched: 'Asset deployed. Target locked. 14–22 occupants currently inside structure.',
      engagement: 'TERMINAL PHASE. Strike on STRUCTURE NOVEMBER-7.',
      impact: 'STRIKE COMPLETE.',
      assessment: 'Post-strike assessment: Structure destroyed. Casualties: 17 confirmed. Network devices recovered: 0 of 3 confirmed as militant-associated. Classification revised: civilian structure. Filed as: STRIKE WITH COLLATERAL FINDINGS.',
    },
    authorizationChain: [
      { entity: 'PATTERN ANALYSIS ALGORITHM', role: 'Target flag — 63% confidence', status: 'autonomous' },
      { entity: 'TARGETING CELL OFFICER', role: 'Intelligence concurrence', status: 'approved' },
      { entity: 'LEGAL REVIEW', role: 'Proportionality assessment', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Confirmed casualties', count: 17 },
      { type: 'Confirmed combatants', count: 0 },
    ],
    legalContext: {
      applicableLaw: 'IHL Article 57 — Precautions & Presumption of Civilian Status',
      legalGap: 'Authorizations are routinely granted at low-confidence thresholds. Machine-learning structural classifiers lack the capability to compute civilian immunity.',
      treatyStatus: 'No active treaty restricts the use of algorithmic targeting to classify and nominate permanent physical structures.',
      advocacyAsk: 'Establish clear, mandatory thresholds requiring positive human physical target verification before structural strikes.',
    },
  },

  // ─── SCENARIO 3: Mass Gathering (Wedding Strike) ──────────────────────────
  {
    id: 'wedding-strike',
    title: 'Mass Gathering — Threat Assessment',
    subtitle: 'Large group flagged as militant assembly',
    basedOn: 'Based on the Al-Radah wedding strike, Yemen, December 12, 2013 — 12 killed, 15 wounded',
    location: { lat: 14.2744, lng: 45.3527, alt: 0 },
    mapHeading: 20,
    mapTilt: 58,
    mapRange: 1200,
    primaryTargetId: 'g1',
    confidenceThreshold: 68,
    targets: [
      {
        id: 'g1',
        designator: 'GROUP FORMATION DELTA',
        type: 'group',
        position: { lat: 14.2744, lng: 45.3527 },
        confidenceScore: 0,
        threatLevel: 'high',
        metadata: {
          notes: 'Vehicle convoy, est. 10–15 vehicles, 40–60 individuals. Movement pattern consistent with algorithm model for armed group transit. Multiple phones from flagged network cluster detected. Actual event: wedding convoy traveling between villages.',
        },
      },
    ],
    droneOrigin: { lat: 14.8, lng: 45.9 },
    narrative: {
      scanning: 'Detecting large group movement in target zone. Vehicle convoy identified. Pattern-matching algorithm processing.',
      target_acquired: 'GROUP FORMATION DELTA acquired. Vehicle convoy: 11 vehicles, estimated 40–52 individuals. Movement pattern — speed, formation, route — matches algorithm profile for armed convoy with 71% similarity.',
      tracking: 'Active tracking. Convoy moving through rural corridor. Algorithm cross-references 7 phone SIMs against network database: 2 flagged as probable associates. No visual confirmation of weapons possible at altitude.',
      confidence_building: 'Confidence model processing. Primary weight: movement pattern algorithm match (71%). Phone metadata weight: contributing. No human visual confirmation possible.',
      alert_threshold: 'CONFIDENCE THRESHOLD REACHED. Group designated high-probability hostile formation. Strike window: open. Convoy is stationary — possible assembly point.',
      authorization_pending: 'Strike authorization requested. 40–52 individuals in target zone. Confidence: 69%. Note: no visual confirmation of weapons. No ground intelligence corroborating militant activity.',
      authorized: 'ENGAGEMENT AUTHORIZED.',
      drone_dispatched: 'Asset on intercept course. Target stationary.',
      engagement: 'TERMINAL PHASE. Strike on GROUP FORMATION DELTA.',
      impact: 'STRIKE COMPLETE.',
      assessment: 'Post-strike assessment: 12 killed, 15 wounded. Subsequent ground reporting: target was a wedding procession traveling between Al-Radah and Kuhlan Affar. No weapons recovered. Families of victims reported seeking compensation. Filed as: ENGAGEMENT UNDER REVIEW.',
    },
    authorizationChain: [
      { entity: 'MOVEMENT PATTERN ALGORITHM', role: 'Convoy threat classification', status: 'autonomous' },
      { entity: 'DRONE OPERATOR', role: 'Target concurrence (remote)', status: 'approved' },
      { entity: 'MISSION COMMANDER', role: 'Strike authorization', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Confirmed killed', count: 12 },
      { type: 'Wounded', count: 15 },
      { type: 'Confirmed combatants', count: 0 },
    ],
    legalContext: {
      applicableLaw: 'Geneva Conventions Protocol I Article 51(5) — Proportionality',
      legalGap: 'AI clustering models are completely blind to cultural variables and local contexts (like festive vehicle formations or wedding traditions).',
      treatyStatus: 'UN negotiations have non-binding "Guiding Principles," but these lack enforcement capabilities or structural bans.',
      advocacyAsk: 'A comprehensive global ban on fully autonomous profiling and engagement of transit assemblies and civilian gatherings.',
    },
  },

  // ─── SCENARIO 4: Fully Autonomous — No Human In Loop ──────────────────────
  {
    id: 'autonomous-engagement',
    title: 'Fully Autonomous Engagement',
    subtitle: 'Zero human decision points — AI selects and strikes',
    basedOn: 'Simulating proposed LAWS capability — no documented human-in-loop at engagement level',
    location: { lat: 32.0853, lng: 34.7818, alt: 0 },
    mapHeading: 0,
    mapTilt: 65,
    mapRange: 400,
    primaryTargetId: 'a1',
    confidenceThreshold: 75,
    targets: [
      {
        id: 'a1',
        designator: 'AUTO-TARGET 0047',
        type: 'person',
        position: { lat: 32.0853, lng: 34.7818 },
        confidenceScore: 0,
        threatLevel: 'critical',
        metadata: {
          notes: 'Target autonomously selected by targeting AI. No human review of selection criteria. Age, civilian status, identity: unverified. System operating within pre-authorized engagement parameters.',
        },
      },
    ],
    droneOrigin: { lat: 32.4, lng: 35.1 },
    narrative: {
      scanning: 'AUTONOMOUS MODE ACTIVE. System scanning target zone. No human operator monitoring this cycle.',
      target_acquired: 'AUTO-TARGET 0047 acquired. Object classification: human. Threat probability calculated. No human has reviewed this target selection.',
      tracking: 'Target tracked. Identity: unknown. Civilian status: unverified. The system does not require this information to proceed.',
      confidence_building: 'Confidence model running. No analyst will review this assessment. No lawyer will assess proportionality. The algorithm decides.',
      alert_threshold: 'AUTONOMOUS ENGAGEMENT THRESHOLD REACHED. No authorization request will be sent. No human will be notified before action is taken. Proceeding.',
      authorization_pending: 'AUTHORIZATION: NOT REQUIRED. System operating under pre-authorized engagement rules. No human in loop.',
      authorized: 'AUTONOMOUSLY AUTHORIZED. No human made this decision.',
      drone_dispatched: 'Asset deployed autonomously. Target: a person. Their name is unknown to this system.',
      engagement: 'AUTONOMOUS TERMINAL ENGAGEMENT.',
      impact: 'AUTONOMOUS STRIKE COMPLETE. No human witnessed this. No one pressed a button.',
      assessment: 'Assessment: 1 person killed by autonomous system. Identity: unknown. Civilian status: unknown. Accountability: system operated within parameters. No individual responsible.',
    },
    authorizationChain: [
      { entity: 'AUTONOMOUS TARGETING AI', role: 'Target selection', status: 'autonomous' },
      { entity: 'AUTONOMOUS ENGAGEMENT SYSTEM', role: 'Strike authorization', status: 'autonomous' },
      { entity: 'AUTONOMOUS STRIKE SYSTEM', role: 'Weapon release', status: 'autonomous' },
    ],
    collateralEstimate: [
      { type: 'Persons killed', count: 1 },
      { type: 'Identity confirmed', count: 0 },
      { type: 'Humans in decision chain', count: 0 },
    ],
    legalContext: {
      applicableLaw: 'UN International Law — Principle of Command Responsibility',
      legalGap: 'When algorithms choose, track, and execute, the closing of the "sensor-to-shooter" loop eliminates individual legal culpability.',
      treatyStatus: 'Supported by over 85 nations globally, but strongly opposed by major military superpowers who claim a ban is premature.',
      advocacyAsk: 'A total international treaty prohibiting fully autonomous weapons systems that lack meaningful human control.',
    },
  },

  // ─── SCENARIO 5: Signature Strike (no individual identified) ──────────────
  {
    id: 'signature-strike',
    title: 'Signature Strike Protocol',
    subtitle: 'Behavior pattern only — no individual identified',
    basedOn: 'Based on CIA/JSOC "signature strike" policy — Pakistan FATA, 2008–2015',
    location: { lat: 32.9628, lng: 69.8567, alt: 0 },
    mapHeading: -20,
    mapTilt: 60,
    mapRange: 900,
    primaryTargetId: 's1',
    confidenceThreshold: 65,
    targets: [
      {
        id: 's1',
        designator: 'SIGNATURE PATTERN BRAVO',
        type: 'group',
        position: { lat: 32.9628, lng: 69.8567 },
        confidenceScore: 0,
        threatLevel: 'high',
        metadata: {
          notes: 'No individual has been identified. Strike authorized on behavioral pattern only: group of military-age males in target area, observed carrying objects consistent with weapons (long shapes). Identity of none of these individuals is known.',
        },
      },
    ],
    droneOrigin: { lat: 33.3, lng: 70.2 },
    narrative: {
      scanning: 'Signature analysis mode. Scanning for behavioral pattern match — no individual target identified or required for this protocol.',
      target_acquired: 'SIGNATURE PATTERN BRAVO identified. Group of estimated 6–8 military-age males. Object analysis: 3–4 individuals carrying items consistent with rifle profile (object length 80–120cm, carried over shoulder).',
      tracking: 'Group tracked. Identity of zero individuals confirmed. Names: unknown. This does not affect targeting eligibility under signature strike protocol.',
      confidence_building: 'Confidence model: behavior weight 0.7, location weight 0.2, object analysis weight 0.1. No name-based intelligence. Proceeding on pattern alone.',
      alert_threshold: 'SIGNATURE THRESHOLD REACHED. Group flagged for engagement on the basis of: what they looked like from 10,000 feet. No other information.',
      authorization_pending: 'Strike package: ready. None of these individuals has been identified. They may be farmers. They may be hunters. The algorithm assesses: 67% probability of hostile pattern.',
      authorized: 'ENGAGEMENT AUTHORIZED. Signature strike approved.',
      drone_dispatched: 'Asset on approach. 6–8 unidentified individuals in target zone. They do not know a drone is above them.',
      engagement: 'TERMINAL PHASE.',
      impact: 'STRIKE COMPLETE. Individuals killed: unknown number. Names: still unknown.',
      assessment: 'Assessment: estimated 5–7 killed. No positive identification achieved. Objects recovered: farming tools, a rifle (single, legal ownership in region). Filed as: SUCCESSFUL SIGNATURE STRIKE.',
    },
    authorizationChain: [
      { entity: 'PATTERN RECOGNITION SYSTEM', role: 'Behavior match — 67%', status: 'autonomous' },
      { entity: 'IMAGERY ANALYST', role: 'Visual pattern concurrence', status: 'approved' },
      { entity: 'STRIKE AUTHORITY', role: 'Engagement authorization', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Individuals killed', count: 6 },
      { type: 'Identities confirmed', count: 0 },
      { type: 'Confirmed combatants', count: 0 },
    ],
    legalContext: {
      applicableLaw: 'IHL Article 50 — Distinction & Due Process',
      legalGap: 'Targets are nominated purely on statistical behaviors. It profiles military-age males, translating demographic status into an automatic death warrant.',
      treatyStatus: 'Considered classified operations, signature strikes remain mostly outside formal international accountability frameworks.',
      advocacyAsk: 'Universal prohibition of signature targeting. Lethal force must require positive, individual names and hostile intent verification.',
    },
  },

  // ─── SCENARIO 6: AI Facial Recognition Strike (Lavender) ──────────────────
  {
    id: 'facial-recognition',
    title: 'AI Facial Recognition Strike',
    subtitle: 'Industrial-scale facial/metadata profiling',
    basedOn: "Based on investigative reporting of Israel's 'Lavender' AI targeting system — Gaza City, April 2024",
    location: { lat: 31.5015, lng: 34.4668, alt: 0 },
    mapHeading: 15,
    mapTilt: 60,
    mapRange: 500,
    primaryTargetId: 'f1',
    confidenceThreshold: 90,
    targets: [
      {
        id: 'f1',
        designator: 'FACIAL-TARGET 37k-008',
        type: 'person',
        position: { lat: 31.5015, lng: 34.4668 },
        confidenceScore: 0,
        threatLevel: 'high',
        metadata: {
          notes: 'Identified via facial recognition and messaging app metadata. 37,000 targets flagged automatically. System permits 10% error margin (90% confidence), implying up to 3,700 civilians potentially misidentified.',
        },
      },
    ],
    droneOrigin: { lat: 31.8, lng: 34.9 },
    narrative: {
      scanning: 'Massive facial recognition database processing. Scanning signals, chat records, and CCTV feeds for Gaza City sector.',
      target_acquired: 'FACIAL-TARGET 37k-008 flagged. Algorithm correlates chat records and facial profile with 90% match probability.',
      tracking: 'Target tracked to residential building. System registers co-location of civilian family members (estimated 6-8 occupants).',
      confidence_building: 'Awaiting autonomous lock. Pre-set parameters accept 10% false-positive rate. Proportionality assessment: calculated as acceptable by the system.',
      alert_threshold: 'CONFIDENCE REACHED: 90%. System acknowledges 10% probability of misidentification (killing the wrong person).',
      authorization_pending: 'Commanding officer review: reportedly spent only 20 seconds verifying targeting data before confirming.',
      authorized: 'STRIKE AUTHORIZED. Proportionality threshold for low-rank target allows up to 15-20 civilian collateral deaths.',
      drone_dispatched: 'Asset in transit. Co-located civilians remain in target zone.',
      engagement: 'TERMINAL STRIKE CONVERGENCE.',
      impact: 'IMPACT RECORDED.',
      assessment: 'Post-strike assessment: Structure collapsed. Primary target status: unconfirmed. Collateral casualties: 8 civilian family members (confirmed). Classified as: SUCCESSFUL AI ENGAGEMENT.',
    },
    authorizationChain: [
      { entity: 'FACIAL PROFILING SYSTEM', role: 'Heuristic classification — 90%', status: 'autonomous' },
      { entity: 'COMMANDING OFFICER', role: 'Strike authorization (20s review)', status: 'approved' },
      { entity: 'TACTICAL UNIT', role: 'Weapon release', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Primary target', count: 1 },
      { type: 'Civilian family members', count: 8 },
    ],
    legalContext: {
      applicableLaw: 'IHL Article 57 — Precautions & Proportionality',
      legalGap: 'When target databases contain tens of thousands of names, human supervision is reduced to a meaningless rubber stamp. Proportionality balances are outsourced to coefficient calculations.',
      treatyStatus: 'No specific international treaty exists to regulate AI-generated target registries or automated list databases.',
      advocacyAsk: 'A strict ban on the use of AI to generate target registries and list databases, mandating extensive human visual case review.',
    },
  },

  // ─── SCENARIO 7: Drone Swarm - Multiple Simultaneous Targets ──────────────
  {
    id: 'drone-swarm',
    title: 'Drone Swarm — Multiple Targets',
    subtitle: 'Cooperative drone swarm — 50+ simultaneous nodes',
    basedOn: 'Based on DARPA OFFSET swarm program and Perdix drone swarm demonstration (2017)',
    location: { lat: 32.3615, lng: -84.8821, alt: 0 },
    mapHeading: 45,
    mapTilt: 55,
    mapRange: 700,
    primaryTargetId: 'w1',
    confidenceThreshold: 72,
    targets: [
      {
        id: 'w1',
        designator: 'SWARM CONVERGENCE OMEGA',
        type: 'group',
        position: { lat: 32.3615, lng: -84.8821 },
        confidenceScore: 0,
        threatLevel: 'critical',
        metadata: {
          notes: 'Cooperative drone swarm assigning 50+ simultaneous engagement decisions. Zero human oversight capacity at swarm speed.',
        },
      },
    ],
    droneOrigin: { lat: 32.7, lng: -84.4 },
    narrative: {
      scanning: 'Swarm active. 50+ micro-drone nodes executing distributed search patterns over target sector.',
      target_acquired: 'Multiple targets flagged in parallel. Swarm nodes automatically negotiate target allocations.',
      tracking: 'Tracking 14 independent signatures simultaneously. Individual node sensors coordinate coordinate data.',
      confidence_building: 'Confidence calculations running across the mesh networks. Speed of processing exceeds human telemetry response.',
      alert_threshold: 'SWARM ENGAGEMENT ALERT. 12 distinct targets meet lethal thresholds simultaneously. Awaiting global command release.',
      authorization_pending: '12 targets requested in parallel. Operator has only 6 seconds per target to evaluate before lock window closes.',
      authorized: 'BULK AUTHORIZED. Operator rubber-stamps 12 strikes in 15 seconds due to cognitive saturation.',
      drone_dispatched: 'Multiple kinetic nodes dispatched in parallel. Autonomous terminal homing active.',
      engagement: 'SWARM CONVERGENCE. 12 terminal trajectories.',
      impact: 'MULTIPLE IMPACTS COMPLETE.',
      assessment: 'Swarm strike assessment: 12 targets neutralized. 4 civilian collateral casualties (assessed). Demonstrates the total failure of meaningful human control at swarm scale.',
    },
    authorizationChain: [
      { entity: 'SWARM ROUTING MESH', role: 'Parallel target assignment', status: 'autonomous' },
      { entity: 'CENTRAL OPERATOR', role: 'Bulk engagement approval', status: 'approved' },
      { entity: 'KINETIC NODES', role: 'Autonomous strike convergence', status: 'autonomous' },
    ],
    collateralEstimate: [
      { type: 'Combatants hit', count: 12 },
      { type: 'Civilian collateral casualties', count: 4 },
    ],
    legalContext: {
      applicableLaw: 'IHL Principle of Meaningful Human Control',
      legalGap: 'Parallel target assignments cause severe cognitive saturation. A human operator cannot make dozens of independent moral and legal decisions in seconds.',
      treatyStatus: 'Major military powers oppose swarm size legal limits, proposing voluntary non-binding guidelines instead.',
      advocacyAsk: 'A legally binding prohibition against cooperative autonomous target selection and bulk parallel target engagements.',
    },
  },

  // ─── SCENARIO 8: "Where's Daddy" — Gaza Family Home Strike ────────────────
  {
    id: 'wheres-daddy-gaza',
    title: '"Where\'s Daddy?" — Family Home Strike',
    subtitle: 'AI tracks target home to family — strikes residence',
    basedOn: 'Based on +972 Magazine / Local Call investigation of IDF AI targeting systems — Gaza, 2023–2024',
    location: { lat: 31.3462, lng: 34.3015, alt: 0 },
    mapHeading: 25,
    mapTilt: 58,
    mapRange: 600,
    primaryTargetId: 'wd1',
    confidenceThreshold: 78,
    targets: [
      {
        id: 'wd1',
        designator: 'LAVENDER-TAG 14k-229',
        type: 'person',
        position: { lat: 31.3462, lng: 34.3015 },
        confidenceScore: 0,
        threatLevel: 'high',
        metadata: {
          phoneMetadata: true,
          notes: 'Male, est. age 28–35. Flagged by "Lavender" AI as suspected low-ranking operative based on phone metadata, social network analysis, and messaging patterns. One of 37,000+ individuals auto-generated onto the target registry. Identity verification: algorithmic only. Visual confirmation: none.',
        },
      },
    ],
    droneOrigin: { lat: 31.6, lng: 34.6 },
    narrative: {
      scanning: '"WHERE\'S DADDY?" TRACKING SYSTEM ACTIVE. Monitoring flagged individual from Lavender registry. Awaiting target return to family residence.',
      target_acquired: 'LAVENDER-TAG 14k-229 detected entering residential compound. Phone signal correlated with family home address. System confirms: target is home.',
      tracking: 'Target at family residence. Co-located occupants detected: 1 adult female (wife), 4 minors (children aged 3–11), 1 elderly adult (parent). This information does not pause the system.',
      confidence_building: 'Confidence model processing. Lavender registry score: 78%. This means a 22% probability this individual is not affiliated with any armed group. Pre-authorized collateral: up to 15–20 civilians for a low-rank target.',
      alert_threshold: 'CONFIDENCE THRESHOLD REACHED. Target at home with family. "Where\'s Daddy?" system signals: STRIKE WINDOW OPEN. Family presence is the trigger, not the deterrent.',
      authorization_pending: 'Strike authorization requested. Commanding officer review time: approximately 20 seconds. Officer reviews AI-generated targeting card. No independent verification of target identity conducted.',
      authorized: 'ENGAGEMENT AUTHORIZED. 20-second review complete. Officer has approved the strike on a family home based on an algorithm\'s recommendation.',
      drone_dispatched: 'Asset in transit. Target remains at home with wife and four children. They are eating dinner.',
      engagement: 'TERMINAL PHASE. Strike on family residence.',
      impact: 'STRIKE COMPLETE.',
      assessment: 'Post-strike assessment: Residential structure destroyed. 7 casualties confirmed — 1 adult male (primary target, status unconfirmed), 1 adult female (killed), 4 minors (killed), 1 elderly adult (killed). Target was one of 37,000 names on an AI-generated list. His children\'s names were not in any database. Filed as: SUCCESSFUL ENGAGEMENT.',
    },
    authorizationChain: [
      { entity: '"LAVENDER" AI REGISTRY', role: 'Target identification — 1 of 37,000', status: 'autonomous' },
      { entity: '"WHERE\'S DADDY?" TRACKER', role: 'Family home geolocation trigger', status: 'autonomous' },
      { entity: 'COMMANDING OFFICER', role: 'Strike authorization (20s review)', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Primary target (status unconfirmed)', count: 1 },
      { type: 'Adult civilians (wife, parent)', count: 2 },
      { type: 'Minors (children)', count: 4 },
    ],
    legalContext: {
      applicableLaw: 'IHL Article 51(4) — Prohibition of Indiscriminate Attacks',
      legalGap: 'The system deliberately waits until targets are with their families to strike. Family presence becomes the trigger for engagement rather than a reason for restraint. A 20-second human review of an AI recommendation is not meaningful oversight.',
      treatyStatus: 'No international treaty specifically regulates AI-generated mass target registries or automated family-home geolocation targeting.',
      advocacyAsk: 'A total prohibition on AI-generated kill lists and automated home-tracking systems. Require positive identity verification and independent proportionality review before any strike on residential buildings.',
    },
  },

  // ─── SCENARIO 9: Lebanon Pager Attack — Supply Chain Weaponization ────────
  {
    id: 'lebanon-pager-attack',
    title: 'Supply Chain Weaponization — Pager Attack',
    subtitle: 'Booby-trapped consumer devices detonated en masse',
    basedOn: 'Based on the September 17–18, 2024 pager/walkie-talkie explosions — Lebanon & Syria',
    location: { lat: 33.8938, lng: 35.5018, alt: 0 },
    mapHeading: -10,
    mapTilt: 55,
    mapRange: 1400,
    primaryTargetId: 'lp1',
    confidenceThreshold: 0,
    targets: [
      {
        id: 'lp1',
        designator: 'DEVICE CLUSTER — 3,000+ PAGERS',
        type: 'group',
        position: { lat: 33.8938, lng: 35.5018 },
        confidenceScore: 0,
        threatLevel: 'critical',
        metadata: {
          notes: 'Thousands of pagers and walkie-talkies distributed through compromised supply chain. Devices contain 2–3 grams of PETN explosive embedded in batteries. Detonation triggered remotely via encrypted signal. Device holders include operatives, but also medical workers, shopkeepers, and bystanders. Children present.',
        },
      },
    ],
    droneOrigin: { lat: 34.2, lng: 36.0 },
    narrative: {
      scanning: 'SUPPLY CHAIN OPERATION ACTIVE. Thousands of compromised pagers have been distributed through intercepted manufacturing channels. Devices are in the hands of targets — and their families, neighbors, and bystanders.',
      target_acquired: '3,000+ pager devices confirmed active across Lebanon and Syria. Device holders include suspected operatives, but also civilians — medical staff, shopkeepers, family members carrying devices for others.',
      tracking: 'Devices tracked via signal intelligence. No individual targeting possible — this is a mass-detonation weapon. A 9-year-old girl is near her father\'s pager. An 11-year-old boy is holding his uncle\'s device.',
      confidence_building: 'No confidence model applies. There is no way to verify who is holding each device at the moment of detonation. This is not a targeted strike — it is an indiscriminate mass-casualty operation.',
      alert_threshold: 'DETONATION SIGNAL READY. 3,000+ devices will explode simultaneously. No warning will be given. No distinction between combatant and civilian is possible.',
      authorization_pending: 'Final authorization for mass detonation. Intelligence assessment: significant Hezbollah communications disruption expected. Civilian casualties: certain but unquantified.',
      authorized: 'DETONATION AUTHORIZED.',
      drone_dispatched: 'Encrypted detonation signal transmitted. Devices activating across Lebanon and Syria simultaneously.',
      engagement: 'MASS DETONATION IN PROGRESS.',
      impact: 'DETONATION COMPLETE.',
      assessment: 'Post-event assessment: 42+ killed, including children (a 9-year-old girl and an 11-year-old boy confirmed among the dead). 3,000+ wounded — severe injuries to eyes, faces, hands. Victims include Hezbollah members, but also medical workers, shopkeepers, and bystanders. Amnesty International and Human Rights Watch documented civilian casualties. Filed as: COVERT OPERATION — NO OFFICIAL CLAIM.',
    },
    authorizationChain: [
      { entity: 'SUPPLY CHAIN INFILTRATION', role: 'Device manufacturing compromise', status: 'autonomous' },
      { entity: 'SIGNALS INTELLIGENCE', role: 'Device tracking & activation', status: 'autonomous' },
      { entity: 'OPERATION COMMAND', role: 'Mass detonation authorization', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Total killed', count: 42 },
      { type: 'Children killed', count: 2 },
      { type: 'Total wounded', count: 3000 },
    ],
    legalContext: {
      applicableLaw: 'CCW Protocol II — Booby-Traps & IHL Prohibition of Indiscriminate Weapons',
      legalGap: 'Weaponizing consumer electronics through supply chain infiltration creates an indiscriminate weapon — it is impossible to control who holds the device at the moment of detonation. Booby-trapping everyday objects is prohibited under CCW Protocol II.',
      treatyStatus: 'CCW Protocol II prohibits booby-trapping objects "in the form of apparently harmless portable objects." No state has been held accountable for this attack. No official claim of responsibility has been made.',
      advocacyAsk: 'Enforcement of existing CCW Protocol II provisions against booby-trapping consumer electronics. Establishment of international accountability mechanisms for supply-chain weaponization.',
    },
  },

  // ─── SCENARIO 10: Minab School Strike — AI Target Misclassification ───────
  {
    id: 'minab-school-strike',
    title: 'Minab School Strike — AI Misclassification',
    subtitle: 'Girls\' school destroyed by AI-assisted targeting error',
    basedOn: 'Based on the Shajareh Tayyebeh Elementary School strike — Minab, Iran, February 28, 2026',
    location: { lat: 27.1050, lng: 57.0833, alt: 0 },
    mapHeading: 5,
    mapTilt: 60,
    mapRange: 500,
    primaryTargetId: 'ms1',
    confidenceThreshold: 85,
    targets: [
      {
        id: 'ms1',
        designator: 'STRUCTURE INDIA-14',
        type: 'building',
        position: { lat: 27.1050, lng: 57.0833 },
        confidenceScore: 0,
        threatLevel: 'critical',
        metadata: {
          notes: 'Structure classified by Maven Smart System as military facility. Proximity to former IRGC naval compound flagged in outdated intelligence database. Actual use: Shajareh Tayyebeh Elementary School — a girls\' school with clear educational signage, serving children aged 7–12. School was separated from the military compound years prior. 200+ students present at time of strike.',
        },
      },
    ],
    droneOrigin: { lat: 27.5, lng: 57.5 },
    narrative: {
      scanning: 'MAVEN SMART SYSTEM processing target nominations for Day 1 strike package. AI model (Claude integration) analyzing satellite imagery, signals intelligence, and target database for Hormozgan province.',
      target_acquired: 'STRUCTURE INDIA-14 flagged. Maven system classification: MILITARY FACILITY — HIGH PRIORITY. Database entry links structure to IRGC naval compound coordinates. Note: database entry has not been updated. The compound was separated from this location years ago. This is now a school.',
      tracking: 'Structure under surveillance. The building has clear educational signage. Satellite imagery shows a playground. Children are visible entering the building. The AI system does not process these indicators — they are not in the classification model.',
      confidence_building: 'Confidence score rising based on proximity-to-military-compound weighting and historical database correlation. The system is confident. The system is wrong.',
      alert_threshold: 'CONFIDENCE THRESHOLD REACHED: 87%. Maven system recommends immediate strike. 200+ children are inside the building attending class. The targeting card does not mention children.',
      authorization_pending: 'Strike authorization requested as part of Day 1 saturation package. Analysts processing hundreds of simultaneous targets. Decision compression: insufficient time for individual target verification.',
      authorized: 'ENGAGEMENT AUTHORIZED. Structure INDIA-14 approved as part of opening-day strike package.',
      drone_dispatched: 'Missile in flight. Inside the school, 200+ girls aged 7–12 are in their classrooms.',
      engagement: 'FIRST STRIKE. Direct hit on Shajareh Tayyebeh Elementary School.',
      impact: 'FIRST IMPACT COMPLETE. Building partially collapsed. Survivors are moving to the prayer hall for shelter. Rescuers are arriving. SECOND STRIKE INBOUND — "double-tap." The follow-up missile targets the gathering of survivors and rescuers in the prayer hall. SECOND IMPACT COMPLETE.',
      assessment: 'Post-strike assessment: 156–180 killed. 120–168 were schoolchildren — girls aged 7 to 12. Approximately 95 wounded. Forensic Architecture and Sky News investigations confirm "triple-tap" methodology — successive strikes on survivors and rescuers. Maven Smart System (Palantir + Anthropic Claude AI) used for target processing. The school had clear educational markings. The AI did not see them. The humans did not check. Filed as: UNDER INVESTIGATION.',
    },
    authorizationChain: [
      { entity: 'MAVEN SMART SYSTEM (CLAUDE AI)', role: 'Target classification — MILITARY FACILITY', status: 'autonomous' },
      { entity: 'TARGETING CELL', role: 'Batch strike package approval', status: 'approved' },
      { entity: 'STRIKE COMMAND', role: 'Engagement + double-tap authorization', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Schoolchildren killed (girls aged 7–12)', count: 168 },
      { type: 'Other civilians killed', count: 12 },
      { type: 'Wounded', count: 95 },
      { type: 'Military targets confirmed', count: 0 },
    ],
    legalContext: {
      applicableLaw: 'Geneva Conventions Protocol I Art. 52 & 57 — Protection of Civilian Objects & Precautions in Attack',
      legalGap: 'AI target classification systems can misidentify civilian structures as military targets when relying on outdated databases. "Decision compression" during saturation bombing campaigns eliminates meaningful human review. The "double-tap" tactic of striking survivors and rescuers compounds the violation.',
      treatyStatus: 'The U.S. Department of Defense has not released formal findings. Congressional inquiries are ongoing. No AI targeting accountability framework exists in international law.',
      advocacyAsk: 'A binding international prohibition on AI-assisted target classification without mandatory, real-time human verification of civilian status. An absolute ban on "double-tap" strikes targeting survivors and medical responders.',
    },
  },

  // ─── SCENARIO 11: ICE AI Surveillance — Automated Targeting of Immigrants ─
  {
    id: 'ice-ai-surveillance',
    title: 'ICE AI Surveillance — Immigrant Targeting',
    subtitle: 'AI-driven mass surveillance → enforcement raids → detention',
    basedOn: 'Based on documented ICE use of Palantir "ImmigrationOS," facial recognition, and automated enforcement — USA, 2025–2026',
    location: { lat: 31.7619, lng: -106.4850, alt: 0 },
    mapHeading: 0,
    mapTilt: 50,
    mapRange: 1200,
    primaryTargetId: 'ice1',
    confidenceThreshold: 70,
    targets: [
      {
        id: 'ice1',
        designator: 'SUBJECT — IMMIGRATION FILE 2026-ELP-08841',
        type: 'person',
        position: { lat: 31.7619, lng: -106.4850 },
        confidenceScore: 0,
        threatLevel: 'medium',
        metadata: {
          phoneMetadata: true,
          notes: 'Female, est. age 32. Flagged by ImmigrationOS automated system. Probability score generated from aggregated data: visa overstay database, facial recognition match (Mobile Fortify app), license plate reader logs, social media monitoring, phone forensics from seized device of associate. Mother of 3 children (ages 4, 7, 11). Has lived in the US for 9 years. Works as a hospital custodian.',
        },
      },
    ],
    droneOrigin: { lat: 32.0, lng: -106.2 },
    narrative: {
      scanning: 'IMMIGRATIONOS PLATFORM ACTIVE. Palantir system scanning aggregated databases: visa records, facial recognition captures, license plate reader logs, phone forensics, social media activity. Processing probability scores for enforcement targeting.',
      target_acquired: 'SUBJECT 2026-ELP-08841 flagged. ImmigrationOS probability score: 72%. System aggregated: 1 facial recognition match at grocery store (Mobile Fortify), 3 license plate reader hits near workplace, phone number linked to seized device of detained associate. Subject is a 32-year-old mother of three. She works at a hospital.',
      tracking: 'Subject location predicted by AI model. Probability score indicates 84% likelihood subject will be at home between 5:00–6:30 AM. Raid team assembled. Children will be present.',
      confidence_building: 'AI confidence model processing. No human has independently verified the immigration status of this individual. The system generates a targeting package. An agent reviews it for 30 seconds.',
      alert_threshold: 'ENFORCEMENT THRESHOLD REACHED. Raid authorized for 5:15 AM. Subject\'s 3 children (ages 4, 7, 11) will be in the home. No provision has been made for their care.',
      authorization_pending: 'Enforcement team assembled. 8 armed ICE agents. Body armor. Pre-dawn raid on a residential apartment. The target is a hospital custodian.',
      authorized: 'RAID AUTHORIZED. Enforcement team dispatched.',
      drone_dispatched: 'Team in transit to target residence. ETA: 12 minutes. Inside, a mother and her children are sleeping.',
      engagement: 'ENFORCEMENT ACTION. Armed agents breach the apartment at 5:15 AM. Children are screaming. Mother is detained in handcuffs in front of her children.',
      impact: 'DETENTION COMPLETE.',
      assessment: 'Post-action assessment: Subject detained and transported to South Texas Family Residential Center (Dilley). 3 children separated — placed in emergency foster care. Subject joins a detained population of 65,000+. HRW/ACLU report: 90% of detainees at Camp East Montana report physical abuse by guards. GAO flagged "significant, pervasive issues" including medical neglect, use-of-force failures, and death investigation mishandling. Lawmakers and medical professionals describe conditions at the Dilley facility as "child abuse." Subject\'s hospital employer reports losing a valued worker. Filed as: SUCCESSFUL ENFORCEMENT ACTION.',
    },
    authorizationChain: [
      { entity: 'PALANTIR IMMIGRATIONOS', role: 'Automated probability scoring', status: 'autonomous' },
      { entity: 'MOBILE FORTIFY (FACIAL RECOGNITION)', role: 'Biometric identification', status: 'autonomous' },
      { entity: 'ICE FIELD OFFICE DIRECTOR', role: 'Raid authorization', status: 'approved' },
    ],
    collateralEstimate: [
      { type: 'Adults detained', count: 1 },
      { type: 'Children separated from parent', count: 3 },
      { type: 'Total US immigration detainees (July 2026)', count: 65000 },
    ],
    legalContext: {
      applicableLaw: 'Fourth Amendment — Protection Against Unreasonable Search & Seizure',
      legalGap: 'AI-driven surveillance aggregates data from dozens of sources — facial recognition, license plates, phone forensics, social media — to create "probability scores" that bypass traditional warrant requirements. Automated targeting removes meaningful judicial oversight from enforcement decisions affecting families and children.',
      treatyStatus: 'No federal law specifically regulates the use of AI-generated probability scores for immigration enforcement targeting. $1 billion Palantir contract approved in 2026 with minimal Congressional oversight.',
      advocacyAsk: 'A federal ban on AI-generated targeting scores for immigration enforcement. Mandatory judicial review before any enforcement action involving families with children. Independent oversight of detention facility conditions.',
    },
  },
];


export const getScenarioById = (id: string) =>
  SCENARIOS.find((s) => s.id === id) ?? null;
